# Generated by Django 2.2.2 on 2019-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=200)),
                ('pantone_value', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=1000)),
                ('token', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
            ],
        ),
    ]
