# Generated by Django 2.2.2 on 2019-06-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='data_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='data_id',
        ),
    ]
