# Generated by Django 2.2.2 on 2019-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_users_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='job',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
