# Generated by Django 2.2.2 on 2019-06-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_users_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='page',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='pantone_value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='job',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='page',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
