# Generated by Django 2.2.2 on 2019-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20190622_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
