export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_TOTAL_PAGES = "RETRIEVE_TOTAL_PAGES";
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";